//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerHosting
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamPaper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamPaper()
        {
            this.Questions = new HashSet<Question>();
            this.StudentInformations = new HashSet<StudentInformation>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> TotalQuestions { get; set; }
        public Nullable<int> TimeDuration { get; set; }
        public Nullable<int> MarksPerQuestion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentInformation> StudentInformations { get; set; }
    }
}
