//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityLayerSqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInformation
    {
        public long StudentCnic { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Batch { get; set; }
        public Nullable<long> PhoneNo { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Address { get; set; }
        public byte[] StudentImage { get; set; }
    }
}
